// Mocks generated by Mockito 5.4.4 from annotations
// in interview_pro_app/test/shared/data/services/default_question_bank_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:interview_pro_app/shared/domain/entities/entities.dart' as _i4;
import 'package:interview_pro_app/shared/domain/repositories/question_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [QuestionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuestionRepository extends _i1.Mock
    implements _i2.QuestionRepository {
  MockQuestionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Question>> getAllQuestions() => (super.noSuchMethod(
        Invocation.method(
          #getAllQuestions,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
      ) as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<_i4.Question?> getQuestionById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getQuestionById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Question?>.value(),
      ) as _i3.Future<_i4.Question?>);

  @override
  _i3.Future<void> saveQuestion(_i4.Question? question) => (super.noSuchMethod(
        Invocation.method(
          #saveQuestion,
          [question],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateQuestion(_i4.Question? question) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuestion,
          [question],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteQuestion(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteQuestion,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Question>> getQuestionsByCategory(
          _i4.QuestionCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionsByCategory,
          [category],
        ),
        returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
      ) as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<List<_i4.Question>> getQuestionsByRole(_i4.Role? role) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionsByRole,
          [role],
        ),
        returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
      ) as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<List<_i4.Question>> getQuestionsByLevel(_i4.Level? level) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionsByLevel,
          [level],
        ),
        returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
      ) as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<List<_i4.Question>> getQuestionsByRoleAndLevel(
    _i4.Role? role,
    _i4.Level? level,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionsByRoleAndLevel,
          [
            role,
            level,
          ],
        ),
        returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
      ) as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<List<_i4.Question>> getQuestionsByCategoryAndRole(
    _i4.QuestionCategory? category,
    _i4.Role? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionsByCategoryAndRole,
          [
            category,
            role,
          ],
        ),
        returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
      ) as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<List<_i4.Question>> getQuestionsByCategoryRoleAndLevel(
    _i4.QuestionCategory? category,
    _i4.Role? role,
    _i4.Level? level,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionsByCategoryRoleAndLevel,
          [
            category,
            role,
            level,
          ],
        ),
        returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
      ) as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<List<_i4.Question>> searchQuestions(String? searchText) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchQuestions,
          [searchText],
        ),
        returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
      ) as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<List<_i4.Question>> getQuestionsByTags(List<String>? tags) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionsByTags,
          [tags],
        ),
        returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
      ) as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<List<_i4.Question>> getRandomQuestions(
    _i4.Role? role,
    _i4.Level? level, {
    int? count = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomQuestions,
          [
            role,
            level,
          ],
          {#count: count},
        ),
        returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
      ) as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<int> getQuestionCount() => (super.noSuchMethod(
        Invocation.method(
          #getQuestionCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getQuestionCountByCategory(_i4.QuestionCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionCountByCategory,
          [category],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getQuestionCountByRole(_i4.Role? role) => (super.noSuchMethod(
        Invocation.method(
          #getQuestionCountByRole,
          [role],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getQuestionCountByLevel(_i4.Level? level) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionCountByLevel,
          [level],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> questionExists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #questionExists,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> saveQuestions(List<_i4.Question>? questions) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveQuestions,
          [questions],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
